---

- name: Create BookStack directory
  file:
    path: "{{ item.split(':')[0] }}"
    state: directory
  loop: "{{ bookstack_volumes }}"

- name: Set Docker container parameters
  set_fact:
    bookstack_container_parameters:
      name: "{{ bookstack_name }}"
      image: "{{ bookstack_image }}"
      state: started
      published_ports: "{{ bookstack_ports | default(omit) }}"
      volumes: "{{ bookstack_volumes | default(omit) }}"
      env: "{{ bookstack_environment_variables | default(omit) }}"

- name: Create BookStack container
  docker_container: "{{ bookstack_container_parameters | combine(bookstack_docker_additional_options) }}"
  register: bookstack_container
